import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Web Developer Portfolio</title>
        <meta
          name="description"
          content="Portfolio of a web developer specializing in modern web applications and AI integration."
        />
        <link rel="icon" type="image/svg+xml" href="/k.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]`}
      >
        {children}
      </body>
    </html>
  );
}
